package andry.hais.shopapi.config;

import andry.hais.shopapi.dto.NewsDTO;
import andry.hais.shopapi.dto.ProductInfoDTO;
import andry.hais.shopapi.entity.User;
import andry.hais.shopapi.service.CommentsService;
import andry.hais.shopapi.service.NewsService;
import andry.hais.shopapi.service.ProductService;
import andry.hais.shopapi.service.UserService;
import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.security.config.annotation.method.configuration.EnableGlobalMethodSecurity;
import org.springframework.security.config.annotation.method.configuration.GlobalMethodSecurityConfiguration;

import java.math.BigDecimal;
import java.util.Arrays;
import java.util.List;

@Configuration
@EnableGlobalMethodSecurity(prePostEnabled = true)
public class AppConfig extends GlobalMethodSecurityConfiguration {

    @Bean
    public CommandLineRunner demo(final ProductService productService,
                                  final UserService userService,
                                  final CommentsService commentsService, final NewsService newsService) {
        return strings -> {
            userService.save(new User("email1@gmail.com", "1234", "name1", "1234121", "city1", "address1", true, "ROLE_CUSTOMER"));
            userService.save(new User("email2@gmail.com", "1111", "name2", "12341234", "city2", "address2", true, "ROLE_ADMIN"));


            List<NewsDTO> News = Arrays.asList(
                    NewsDTO.of("https://answear.ua/blog/wp-content/uploads/2020/07/Summer_outdoor_PL_02.jpg", "https://answear.ua/blog/wp-content/uploads/2020/07/Summer_outdoor_PL_05.jpg", "https://answear.ua/blog/wp-content/uploads/2020/07/large_img_2381307.jpg", "Літня прогулянка: який look обрати?", "Літо сприяє активному відпочинку! Перевірте, як весело та стильно провести час, гуляючи на природі… Або може оберете велосипед? А Ви як любите проводити свій вільний час?", "https://answear.ua/blog/wp-content/uploads/2020/07/Summer_outdoor_PL_25.jpg", "https://answear.ua/blog/wp-content/uploads/2020/07/Summer_outdoor_PL_45.jpg", "Комфорт – це ключове слово, якщо говоримо про літній активний відпочинок та відповідність стилів. Незалежно від того, чи просто збираєтеся на невелику прогулянку чи проведете цілий день на природі, те, що Ви одягнете, грає велику роль. Вдало підібрані елементи гардеробу дозволять Вам не тільки блищати чудовими стилями, а насамперед, відчувати себе безпечно і комфортно у всіх, навіть несподіваних умовах.")
            );
            newsService.addNews(News);


            List<ProductInfoDTO> Products = Arrays.asList(
                    // men-home
                    // t-shirts
                    ProductInfoDTO.of("TS001", "https://shift.ua/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/i/m/img_8900.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/i/m/img_8889.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/i/m/img_8893.jpg", "men-home", "t-shirts", "Футболка Shift Sport Hound White", "Натуральный хлопок.", "Модель прямого кроя изготовлена из воздухопроницаемого джерси. Традиционный дизайн сопровождается круглым эластичным воротом. Яркий акцент дополняют контрастный принт. Идеально подойдет для тренировки.", "XS, S, M, L", new BigDecimal("599"), new BigDecimal("25"), 100),
                    ProductInfoDTO.of("TS002", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/e/z/ezgif-3-77f31fc0c1e2.png", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/e/z/ezgif-3-2e63fb5cb647.png", "https://shift.ua/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/e/z/ezgif-3-9592e521ee45.png", "men-home", "t-shirts", "Футболка The North Face Light Tee Black", "Натуральный хлопок.", "Футболка  выполнена из натурального хлопка. У модели эластичный ворот. Базовая вещь, которая будет органично смотреться с джинсами в межсезонье, и с шортами летом.", "XS, S, M, L", new BigDecimal("1299"), new BigDecimal("0"), 100),
                    ProductInfoDTO.of("TS003", "https://shift.ua/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/m/a/main_2__2.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/2/_/2_2__2.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/2/_/2_2__2.jpg", "men-home", "t-shirts", "Футболка Timberland YC Established 1973 SS Tee White/Surf the Web", "Натуральный хлопок.", "Модель прямого кроя изготовлена из воздухопроницаемого джерси. Традиционный дизайн сопровождается круглым эластичным воротом. Яркий акцент дополняют контрастный принт. Идеально подойдет для тренировки.", "XS, S, M, L", new BigDecimal("699"), new BigDecimal("20"), 100),
                    ProductInfoDTO.of("TS004", "https://shift.ua/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/m/a/main_1__2.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/1/_/1_1__3.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/2/_/2_1__3.jpg", "men-home", "t-shirts", "Футболка Timberland SS Cut & Sew Colorblock Tee Deep Mint/Surf the Web", "Натуральный хлопок.", "Мужская футболка Timberland, выполненная из натурального хлопка. Модель имеет прямой крой и круглый эластичный ворот, дополнена контрастным принтом.", "XS, S, M, L", new BigDecimal("999"), new BigDecimal("20"), 100),
                    ProductInfoDTO.of("TS005", "https://shift.ua/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/i/m/img_8900.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/i/m/img_8889.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/i/m/img_8893.jpg", "men-home", "t-shirts", "Футболка Shift Sport Hound White", "Натуральный хлопок.", "Модель прямого кроя изготовлена из воздухопроницаемого джерси. Традиционный дизайн сопровождается круглым эластичным воротом. Яркий акцент дополняют контрастный принт. Идеально подойдет для тренировки.", "XS, S, M, L", new BigDecimal("599"), new BigDecimal("15"), 0),
                    ProductInfoDTO.of("TS006", "https://shift.ua/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/3/_/3_7_11.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/2/_/2_4_2.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/m/a/main_6.jpg", "men-home", "t-shirts", "Футболка Timberland SS Street Photo Graphic Tee White", "Натуральный хлопок.", "Мужская футболка Timberland, выполненная из натурального хлопка. Модель имеет прямой крой и круглый эластичный ворот, дополнена контрастным принтом.", "XS, S, M, L", new BigDecimal("999"), new BigDecimal("0"), 100),
                    ProductInfoDTO.of("TS007", "https://shift.ua/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/3/_/3_1__2.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/1/_/1_1__2.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/2/_/2_1__2.jpg", "men-home", "t-shirts", "Футболка Timberland SS Wild Camo AOP Tee (Relaxed) Burnt Olive Wild Camo Print", "Натуральный хлопок.", "Мужская футболка Timberland, выполненная из натурального хлопка. Модель имеет прямой крой и круглый эластичный ворот, дополнена контрастным принтом.", "XS, S, M, L", new BigDecimal("1199"), new BigDecimal("10"), 100),
                    ProductInfoDTO.of("TS008", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/i/m/img_8887.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/i/m/img_8889.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/i/m/img_8893.jpg", "men-home", "t-shirts", "Футболка Shift Sport Hound White", "Натуральный хлопок.", "Модель прямого кроя изготовлена из воздухопроницаемого джерси. Традиционный дизайн сопровождается круглым эластичным воротом. Яркий акцент дополняют контрастный принт. Идеально подойдет для тренировки.", "XS, S, M, L", new BigDecimal("999"), new BigDecimal("40"), 0),

                    //test pagination
                    ProductInfoDTO.of("TS0101", "https://shift.ua/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/i/m/img_8900.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/i/m/img_8889.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/i/m/img_8893.jpg", "men-home", "t-shirts", "Футболка Shift Sport Hound White", "Натуральный хлопок.", "Модель прямого кроя изготовлена из воздухопроницаемого джерси. Традиционный дизайн сопровождается круглым эластичным воротом. Яркий акцент дополняют контрастный принт. Идеально подойдет для тренировки.", "XS, S, M, L", new BigDecimal("599"), new BigDecimal("25"), 100),
                    ProductInfoDTO.of("TS1012", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/e/z/ezgif-3-77f31fc0c1e2.png", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/e/z/ezgif-3-2e63fb5cb647.png", "https://shift.ua/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/e/z/ezgif-3-9592e521ee45.png", "men-home", "t-shirts", "Футболка The North Face Light Tee Black", "Натуральный хлопок.", "Футболка  выполнена из натурального хлопка. У модели эластичный ворот. Базовая вещь, которая будет органично смотреться с джинсами в межсезонье, и с шортами летом.", "XS, S, M, L", new BigDecimal("1299"), new BigDecimal("0"), 100),
                    ProductInfoDTO.of("TS1003", "https://shift.ua/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/m/a/main_2__2.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/2/_/2_2__2.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/2/_/2_2__2.jpg", "men-home", "t-shirts", "Футболка Timberland YC Established 1973 SS Tee White/Surf the Web", "Натуральный хлопок.", "Модель прямого кроя изготовлена из воздухопроницаемого джерси. Традиционный дизайн сопровождается круглым эластичным воротом. Яркий акцент дополняют контрастный принт. Идеально подойдет для тренировки.", "XS, S, M, L", new BigDecimal("699"), new BigDecimal("20"), 100),
                    ProductInfoDTO.of("TS114", "https://shift.ua/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/m/a/main_1__2.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/1/_/1_1__3.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/2/_/2_1__3.jpg", "men-home", "t-shirts", "Футболка Timberland SS Cut & Sew Colorblock Tee Deep Mint/Surf the Web", "Натуральный хлопок.", "Мужская футболка Timberland, выполненная из натурального хлопка. Модель имеет прямой крой и круглый эластичный ворот, дополнена контрастным принтом.", "XS, S, M, L", new BigDecimal("999"), new BigDecimal("20"), 100),
                    ProductInfoDTO.of("TS1005", "https://shift.ua/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/i/m/img_8900.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/i/m/img_8889.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/i/m/img_8893.jpg", "men-home", "t-shirts", "Футболка Shift Sport Hound White", "Натуральный хлопок.", "Модель прямого кроя изготовлена из воздухопроницаемого джерси. Традиционный дизайн сопровождается круглым эластичным воротом. Яркий акцент дополняют контрастный принт. Идеально подойдет для тренировки.", "XS, S, M, L", new BigDecimal("599"), new BigDecimal("15"), 0),
                    ProductInfoDTO.of("TS016", "https://shift.ua/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/3/_/3_7_11.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/2/_/2_4_2.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/m/a/main_6.jpg", "men-home", "t-shirts", "Футболка Timberland SS Street Photo Graphic Tee White", "Натуральный хлопок.", "Мужская футболка Timberland, выполненная из натурального хлопка. Модель имеет прямой крой и круглый эластичный ворот, дополнена контрастным принтом.", "XS, S, M, L", new BigDecimal("999"), new BigDecimal("0"), 100),
                    ProductInfoDTO.of("TS107", "https://shift.ua/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/3/_/3_1__2.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/1/_/1_1__2.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/2/_/2_1__2.jpg", "men-home", "t-shirts", "Футболка Timberland SS Wild Camo AOP Tee (Relaxed) Burnt Olive Wild Camo Print", "Натуральный хлопок.", "Мужская футболка Timberland, выполненная из натурального хлопка. Модель имеет прямой крой и круглый эластичный ворот, дополнена контрастным принтом.", "XS, S, M, L", new BigDecimal("1199"), new BigDecimal("10"), 100),
                    ProductInfoDTO.of("TS081", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/i/m/img_8887.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/i/m/img_8889.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/i/m/img_8893.jpg", "men-home", "t-shirts", "Футболка Shift Sport Hound White", "Натуральный хлопок.", "Модель прямого кроя изготовлена из воздухопроницаемого джерси. Традиционный дизайн сопровождается круглым эластичным воротом. Яркий акцент дополняют контрастный принт. Идеально подойдет для тренировки.", "XS, S, M, L", new BigDecimal("999"), new BigDecimal("40"), 0),
                    ProductInfoDTO.of("TS011", "https://shift.ua/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/i/m/img_8900.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/i/m/img_8889.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/i/m/img_8893.jpg", "men-home", "t-shirts", "Футболка Shift Sport Hound White", "Натуральный хлопок.", "Модель прямого кроя изготовлена из воздухопроницаемого джерси. Традиционный дизайн сопровождается круглым эластичным воротом. Яркий акцент дополняют контрастный принт. Идеально подойдет для тренировки.", "XS, S, M, L", new BigDecimal("599"), new BigDecimal("25"), 100),
                    ProductInfoDTO.of("TS102", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/e/z/ezgif-3-77f31fc0c1e2.png", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/e/z/ezgif-3-2e63fb5cb647.png", "https://shift.ua/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/e/z/ezgif-3-9592e521ee45.png", "men-home", "t-shirts", "Футболка The North Face Light Tee Black", "Натуральный хлопок.", "Футболка  выполнена из натурального хлопка. У модели эластичный ворот. Базовая вещь, которая будет органично смотреться с джинсами в межсезонье, и с шортами летом.", "XS, S, M, L", new BigDecimal("1299"), new BigDecimal("0"), 100),
                    ProductInfoDTO.of("TS013", "https://shift.ua/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/m/a/main_2__2.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/2/_/2_2__2.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/2/_/2_2__2.jpg", "men-home", "t-shirts", "Футболка Timberland YC Established 1973 SS Tee White/Surf the Web", "Натуральный хлопок.", "Модель прямого кроя изготовлена из воздухопроницаемого джерси. Традиционный дизайн сопровождается круглым эластичным воротом. Яркий акцент дополняют контрастный принт. Идеально подойдет для тренировки.", "XS, S, M, L", new BigDecimal("699"), new BigDecimal("20"), 100),
                    ProductInfoDTO.of("TS041", "https://shift.ua/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/m/a/main_1__2.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/1/_/1_1__3.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/2/_/2_1__3.jpg", "men-home", "t-shirts", "Футболка Timberland SS Cut & Sew Colorblock Tee Deep Mint/Surf the Web", "Натуральный хлопок.", "Мужская футболка Timberland, выполненная из натурального хлопка. Модель имеет прямой крой и круглый эластичный ворот, дополнена контрастным принтом.", "XS, S, M, L", new BigDecimal("999"), new BigDecimal("20"), 100),
                    ProductInfoDTO.of("TS015", "https://shift.ua/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/i/m/img_8900.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/i/m/img_8889.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/i/m/img_8893.jpg", "men-home", "t-shirts", "Футболка Shift Sport Hound White", "Натуральный хлопок.", "Модель прямого кроя изготовлена из воздухопроницаемого джерси. Традиционный дизайн сопровождается круглым эластичным воротом. Яркий акцент дополняют контрастный принт. Идеально подойдет для тренировки.", "XS, S, M, L", new BigDecimal("599"), new BigDecimal("15"), 0),
                    ProductInfoDTO.of("TS016", "https://shift.ua/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/3/_/3_7_11.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/2/_/2_4_2.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/m/a/main_6.jpg", "men-home", "t-shirts", "Футболка Timberland SS Street Photo Graphic Tee White", "Натуральный хлопок.", "Мужская футболка Timberland, выполненная из натурального хлопка. Модель имеет прямой крой и круглый эластичный ворот, дополнена контрастным принтом.", "XS, S, M, L", new BigDecimal("999"), new BigDecimal("0"), 100),
                    ProductInfoDTO.of("TS071", "https://shift.ua/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/3/_/3_1__2.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/1/_/1_1__2.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/2/_/2_1__2.jpg", "men-home", "t-shirts", "Футболка Timberland SS Wild Camo AOP Tee (Relaxed) Burnt Olive Wild Camo Print", "Натуральный хлопок.", "Мужская футболка Timberland, выполненная из натурального хлопка. Модель имеет прямой крой и круглый эластичный ворот, дополнена контрастным принтом.", "XS, S, M, L", new BigDecimal("1199"), new BigDecimal("10"), 100),
                    ProductInfoDTO.of("TS018", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/i/m/img_8887.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/i/m/img_8889.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/i/m/img_8893.jpg", "men-home", "t-shirts", "Футболка Shift Sport Hound White", "Натуральный хлопок.", "Модель прямого кроя изготовлена из воздухопроницаемого джерси. Традиционный дизайн сопровождается круглым эластичным воротом. Яркий акцент дополняют контрастный принт. Идеально подойдет для тренировки.", "XS, S, M, L", new BigDecimal("999"), new BigDecimal("40"), 0),
                    ProductInfoDTO.of("TS10011", "https://shift.ua/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/i/m/img_8900.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/i/m/img_8889.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/i/m/img_8893.jpg", "men-home", "t-shirts", "Футболка Shift Sport Hound White", "Натуральный хлопок.", "Модель прямого кроя изготовлена из воздухопроницаемого джерси. Традиционный дизайн сопровождается круглым эластичным воротом. Яркий акцент дополняют контрастный принт. Идеально подойдет для тренировки.", "XS, S, M, L", new BigDecimal("599"), new BigDecimal("25"), 100),
                    ProductInfoDTO.of("TS021", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/e/z/ezgif-3-77f31fc0c1e2.png", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/e/z/ezgif-3-2e63fb5cb647.png", "https://shift.ua/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/e/z/ezgif-3-9592e521ee45.png", "men-home", "t-shirts", "Футболка The North Face Light Tee Black", "Натуральный хлопок.", "Футболка  выполнена из натурального хлопка. У модели эластичный ворот. Базовая вещь, которая будет органично смотреться с джинсами в межсезонье, и с шортами летом.", "XS, S, M, L", new BigDecimal("1299"), new BigDecimal("0"), 100),
                    ProductInfoDTO.of("TS013", "https://shift.ua/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/m/a/main_2__2.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/2/_/2_2__2.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/2/_/2_2__2.jpg", "men-home", "t-shirts", "Футболка Timberland YC Established 1973 SS Tee White/Surf the Web", "Натуральный хлопок.", "Модель прямого кроя изготовлена из воздухопроницаемого джерси. Традиционный дизайн сопровождается круглым эластичным воротом. Яркий акцент дополняют контрастный принт. Идеально подойдет для тренировки.", "XS, S, M, L", new BigDecimal("699"), new BigDecimal("20"), 100),
                    ProductInfoDTO.of("TS014", "https://shift.ua/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/m/a/main_1__2.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/1/_/1_1__3.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/2/_/2_1__3.jpg", "men-home", "t-shirts", "Футболка Timberland SS Cut & Sew Colorblock Tee Deep Mint/Surf the Web", "Натуральный хлопок.", "Мужская футболка Timberland, выполненная из натурального хлопка. Модель имеет прямой крой и круглый эластичный ворот, дополнена контрастным принтом.", "XS, S, M, L", new BigDecimal("999"), new BigDecimal("20"), 100),
                    ProductInfoDTO.of("TS0511", "https://shift.ua/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/i/m/img_8900.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/i/m/img_8889.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/i/m/img_8893.jpg", "men-home", "t-shirts", "Футболка Shift Sport Hound White", "Натуральный хлопок.", "Модель прямого кроя изготовлена из воздухопроницаемого джерси. Традиционный дизайн сопровождается круглым эластичным воротом. Яркий акцент дополняют контрастный принт. Идеально подойдет для тренировки.", "XS, S, M, L", new BigDecimal("599"), new BigDecimal("15"), 0),
                    ProductInfoDTO.of("TS0106", "https://shift.ua/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/3/_/3_7_11.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/2/_/2_4_2.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/m/a/main_6.jpg", "men-home", "t-shirts", "Футболка Timberland SS Street Photo Graphic Tee White", "Натуральный хлопок.", "Мужская футболка Timberland, выполненная из натурального хлопка. Модель имеет прямой крой и круглый эластичный ворот, дополнена контрастным принтом.", "XS, S, M, L", new BigDecimal("999"), new BigDecimal("0"), 100),
                    ProductInfoDTO.of("TS107", "https://shift.ua/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/3/_/3_1__2.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/1/_/1_1__2.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/2/_/2_1__2.jpg", "men-home", "t-shirts", "Футболка Timberland SS Wild Camo AOP Tee (Relaxed) Burnt Olive Wild Camo Print", "Натуральный хлопок.", "Мужская футболка Timberland, выполненная из натурального хлопка. Модель имеет прямой крой и круглый эластичный ворот, дополнена контрастным принтом.", "XS, S, M, L", new BigDecimal("1199"), new BigDecimal("10"), 100),
                    ProductInfoDTO.of("TS081", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/i/m/img_8887.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/i/m/img_8889.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/i/m/img_8893.jpg", "men-home", "t-shirts", "Футболка Shift Sport Hound White", "Натуральный хлопок.", "Модель прямого кроя изготовлена из воздухопроницаемого джерси. Традиционный дизайн сопровождается круглым эластичным воротом. Яркий акцент дополняют контрастный принт. Идеально подойдет для тренировки.", "XS, S, M, L", new BigDecimal("999"), new BigDecimal("40"), 0),
                    ProductInfoDTO.of("TS011", "https://shift.ua/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/i/m/img_8900.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/i/m/img_8889.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/i/m/img_8893.jpg", "men-home", "t-shirts", "Футболка Shift Sport Hound White", "Натуральный хлопок.", "Модель прямого кроя изготовлена из воздухопроницаемого джерси. Традиционный дизайн сопровождается круглым эластичным воротом. Яркий акцент дополняют контрастный принт. Идеально подойдет для тренировки.", "XS, S, M, L", new BigDecimal("599"), new BigDecimal("25"), 100),
                    ProductInfoDTO.of("TS102", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/e/z/ezgif-3-77f31fc0c1e2.png", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/e/z/ezgif-3-2e63fb5cb647.png", "https://shift.ua/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/e/z/ezgif-3-9592e521ee45.png", "men-home", "t-shirts", "Футболка The North Face Light Tee Black", "Натуральный хлопок.", "Футболка  выполнена из натурального хлопка. У модели эластичный ворот. Базовая вещь, которая будет органично смотреться с джинсами в межсезонье, и с шортами летом.", "XS, S, M, L", new BigDecimal("1299"), new BigDecimal("0"), 100),
                    ProductInfoDTO.of("TS031", "https://shift.ua/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/m/a/main_2__2.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/2/_/2_2__2.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/2/_/2_2__2.jpg", "men-home", "t-shirts", "Футболка Timberland YC Established 1973 SS Tee White/Surf the Web", "Натуральный хлопок.", "Модель прямого кроя изготовлена из воздухопроницаемого джерси. Традиционный дизайн сопровождается круглым эластичным воротом. Яркий акцент дополняют контрастный принт. Идеально подойдет для тренировки.", "XS, S, M, L", new BigDecimal("699"), new BigDecimal("20"), 100),
                    ProductInfoDTO.of("TS014", "https://shift.ua/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/m/a/main_1__2.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/1/_/1_1__3.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/2/_/2_1__3.jpg", "men-home", "t-shirts", "Футболка Timberland SS Cut & Sew Colorblock Tee Deep Mint/Surf the Web", "Натуральный хлопок.", "Мужская футболка Timberland, выполненная из натурального хлопка. Модель имеет прямой крой и круглый эластичный ворот, дополнена контрастным принтом.", "XS, S, M, L", new BigDecimal("999"), new BigDecimal("20"), 100),
                    ProductInfoDTO.of("TS105", "https://shift.ua/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/i/m/img_8900.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/i/m/img_8889.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/i/m/img_8893.jpg", "men-home", "t-shirts", "Футболка Shift Sport Hound White", "Натуральный хлопок.", "Модель прямого кроя изготовлена из воздухопроницаемого джерси. Традиционный дизайн сопровождается круглым эластичным воротом. Яркий акцент дополняют контрастный принт. Идеально подойдет для тренировки.", "XS, S, M, L", new BigDecimal("599"), new BigDecimal("15"), 0),
                    ProductInfoDTO.of("TS006", "https://shift.ua/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/3/_/3_7_11.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/2/_/2_4_2.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/m/a/main_6.jpg", "men-home", "t-shirts", "Футболка Timberland SS Street Photo Graphic Tee White", "Натуральный хлопок.", "Мужская футболка Timberland, выполненная из натурального хлопка. Модель имеет прямой крой и круглый эластичный ворот, дополнена контрастным принтом.", "XS, S, M, L", new BigDecimal("999"), new BigDecimal("0"), 100),
                    ProductInfoDTO.of("TS071", "https://shift.ua/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/3/_/3_1__2.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/1/_/1_1__2.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/2/_/2_1__2.jpg", "men-home", "t-shirts", "Футболка Timberland SS Wild Camo AOP Tee (Relaxed) Burnt Olive Wild Camo Print", "Натуральный хлопок.", "Мужская футболка Timberland, выполненная из натурального хлопка. Модель имеет прямой крой и круглый эластичный ворот, дополнена контрастным принтом.", "XS, S, M, L", new BigDecimal("1199"), new BigDecimal("10"), 100),
                    ProductInfoDTO.of("TS018", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/i/m/img_8887.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/i/m/img_8889.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/i/m/img_8893.jpg", "men-home", "t-shirts", "Футболка Shift Sport Hound White", "Натуральный хлопок.", "Модель прямого кроя изготовлена из воздухопроницаемого джерси. Традиционный дизайн сопровождается круглым эластичным воротом. Яркий акцент дополняют контрастный принт. Идеально подойдет для тренировки.", "XS, S, M, L", new BigDecimal("999"), new BigDecimal("40"), 0),
                    ProductInfoDTO.of("TS101", "https://shift.ua/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/i/m/img_8900.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/i/m/img_8889.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/i/m/img_8893.jpg", "men-home", "t-shirts", "Футболка Shift Sport Hound White", "Натуральный хлопок.", "Модель прямого кроя изготовлена из воздухопроницаемого джерси. Традиционный дизайн сопровождается круглым эластичным воротом. Яркий акцент дополняют контрастный принт. Идеально подойдет для тренировки.", "XS, S, M, L", new BigDecimal("599"), new BigDecimal("25"), 100),
                    ProductInfoDTO.of("TS02", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/e/z/ezgif-3-77f31fc0c1e2.png", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/e/z/ezgif-3-2e63fb5cb647.png", "https://shift.ua/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/e/z/ezgif-3-9592e521ee45.png", "men-home", "t-shirts", "Футболка The North Face Light Tee Black", "Натуральный хлопок.", "Футболка  выполнена из натурального хлопка. У модели эластичный ворот. Базовая вещь, которая будет органично смотреться с джинсами в межсезонье, и с шортами летом.", "XS, S, M, L", new BigDecimal("1299"), new BigDecimal("0"), 100),
                    ProductInfoDTO.of("TS031", "https://shift.ua/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/m/a/main_2__2.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/2/_/2_2__2.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/2/_/2_2__2.jpg", "men-home", "t-shirts", "Футболка Timberland YC Established 1973 SS Tee White/Surf the Web", "Натуральный хлопок.", "Модель прямого кроя изготовлена из воздухопроницаемого джерси. Традиционный дизайн сопровождается круглым эластичным воротом. Яркий акцент дополняют контрастный принт. Идеально подойдет для тренировки.", "XS, S, M, L", new BigDecimal("699"), new BigDecimal("20"), 100),
                    ProductInfoDTO.of("TS0104", "https://shift.ua/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/m/a/main_1__2.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/1/_/1_1__3.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/2/_/2_1__3.jpg", "men-home", "t-shirts", "Футболка Timberland SS Cut & Sew Colorblock Tee Deep Mint/Surf the Web", "Натуральный хлопок.", "Мужская футболка Timberland, выполненная из натурального хлопка. Модель имеет прямой крой и круглый эластичный ворот, дополнена контрастным принтом.", "XS, S, M, L", new BigDecimal("999"), new BigDecimal("20"), 100),
                    ProductInfoDTO.of("TS105", "https://shift.ua/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/i/m/img_8900.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/i/m/img_8889.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/i/m/img_8893.jpg", "men-home", "t-shirts", "Футболка Shift Sport Hound White", "Натуральный хлопок.", "Модель прямого кроя изготовлена из воздухопроницаемого джерси. Традиционный дизайн сопровождается круглым эластичным воротом. Яркий акцент дополняют контрастный принт. Идеально подойдет для тренировки.", "XS, S, M, L", new BigDecimal("599"), new BigDecimal("15"), 0),
                    ProductInfoDTO.of("TS061", "https://shift.ua/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/3/_/3_7_11.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/2/_/2_4_2.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/m/a/main_6.jpg", "men-home", "t-shirts", "Футболка Timberland SS Street Photo Graphic Tee White", "Натуральный хлопок.", "Мужская футболка Timberland, выполненная из натурального хлопка. Модель имеет прямой крой и круглый эластичный ворот, дополнена контрастным принтом.", "XS, S, M, L", new BigDecimal("999"), new BigDecimal("0"), 100),
                    ProductInfoDTO.of("TS017", "https://shift.ua/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/3/_/3_1__2.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/1/_/1_1__2.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/2/_/2_1__2.jpg", "men-home", "t-shirts", "Футболка Timberland SS Wild Camo AOP Tee (Relaxed) Burnt Olive Wild Camo Print", "Натуральный хлопок.", "Мужская футболка Timberland, выполненная из натурального хлопка. Модель имеет прямой крой и круглый эластичный ворот, дополнена контрастным принтом.", "XS, S, M, L", new BigDecimal("1199"), new BigDecimal("10"), 100),
                    ProductInfoDTO.of("TS108", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/i/m/img_8887.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/i/m/img_8889.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/i/m/img_8893.jpg", "men-home", "t-shirts", "Футболка Shift Sport Hound White", "Натуральный хлопок.", "Модель прямого кроя изготовлена из воздухопроницаемого джерси. Традиционный дизайн сопровождается круглым эластичным воротом. Яркий акцент дополняют контрастный принт. Идеально подойдет для тренировки.", "XS, S, M, L", new BigDecimal("999"), new BigDecimal("40"), 0),
                    ProductInfoDTO.of("TS011", "https://shift.ua/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/i/m/img_8900.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/i/m/img_8889.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/i/m/img_8893.jpg", "men-home", "t-shirts", "Футболка Shift Sport Hound White", "Натуральный хлопок.", "Модель прямого кроя изготовлена из воздухопроницаемого джерси. Традиционный дизайн сопровождается круглым эластичным воротом. Яркий акцент дополняют контрастный принт. Идеально подойдет для тренировки.", "XS, S, M, L", new BigDecimal("599"), new BigDecimal("25"), 100),
                    ProductInfoDTO.of("TS102", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/e/z/ezgif-3-77f31fc0c1e2.png", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/e/z/ezgif-3-2e63fb5cb647.png", "https://shift.ua/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/e/z/ezgif-3-9592e521ee45.png", "men-home", "t-shirts", "Футболка The North Face Light Tee Black", "Натуральный хлопок.", "Футболка  выполнена из натурального хлопка. У модели эластичный ворот. Базовая вещь, которая будет органично смотреться с джинсами в межсезонье, и с шортами летом.", "XS, S, M, L", new BigDecimal("1299"), new BigDecimal("0"), 100),
                    ProductInfoDTO.of("TS013", "https://shift.ua/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/m/a/main_2__2.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/2/_/2_2__2.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/2/_/2_2__2.jpg", "men-home", "t-shirts", "Футболка Timberland YC Established 1973 SS Tee White/Surf the Web", "Натуральный хлопок.", "Модель прямого кроя изготовлена из воздухопроницаемого джерси. Традиционный дизайн сопровождается круглым эластичным воротом. Яркий акцент дополняют контрастный принт. Идеально подойдет для тренировки.", "XS, S, M, L", new BigDecimal("699"), new BigDecimal("20"), 100),
                    ProductInfoDTO.of("TS104", "https://shift.ua/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/m/a/main_1__2.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/1/_/1_1__3.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/2/_/2_1__3.jpg", "men-home", "t-shirts", "Футболка Timberland SS Cut & Sew Colorblock Tee Deep Mint/Surf the Web", "Натуральный хлопок.", "Мужская футболка Timberland, выполненная из натурального хлопка. Модель имеет прямой крой и круглый эластичный ворот, дополнена контрастным принтом.", "XS, S, M, L", new BigDecimal("999"), new BigDecimal("20"), 100),
                    ProductInfoDTO.of("TS051", "https://shift.ua/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/i/m/img_8900.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/i/m/img_8889.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/i/m/img_8893.jpg", "men-home", "t-shirts", "Футболка Shift Sport Hound White", "Натуральный хлопок.", "Модель прямого кроя изготовлена из воздухопроницаемого джерси. Традиционный дизайн сопровождается круглым эластичным воротом. Яркий акцент дополняют контрастный принт. Идеально подойдет для тренировки.", "XS, S, M, L", new BigDecimal("599"), new BigDecimal("15"), 0),
                    ProductInfoDTO.of("TS006", "https://shift.ua/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/3/_/3_7_11.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/2/_/2_4_2.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/m/a/main_6.jpg", "men-home", "t-shirts", "Футболка Timberland SS Street Photo Graphic Tee White", "Натуральный хлопок.", "Мужская футболка Timberland, выполненная из натурального хлопка. Модель имеет прямой крой и круглый эластичный ворот, дополнена контрастным принтом.", "XS, S, M, L", new BigDecimal("999"), new BigDecimal("0"), 100),
                    ProductInfoDTO.of("TS017", "https://shift.ua/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/3/_/3_1__2.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/1/_/1_1__2.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/2/_/2_1__2.jpg", "men-home", "t-shirts", "Футболка Timberland SS Wild Camo AOP Tee (Relaxed) Burnt Olive Wild Camo Print", "Натуральный хлопок.", "Мужская футболка Timberland, выполненная из натурального хлопка. Модель имеет прямой крой и круглый эластичный ворот, дополнена контрастным принтом.", "XS, S, M, L", new BigDecimal("1199"), new BigDecimal("10"), 100),
                    ProductInfoDTO.of("TS108", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/i/m/img_8887.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/i/m/img_8889.jpg", "https://shift.ua/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/i/m/img_8893.jpg", "men-home", "t-shirts", "Футболка Shift Sport Hound White", "Натуральный хлопок.", "Модель прямого кроя изготовлена из воздухопроницаемого джерси. Традиционный дизайн сопровождается круглым эластичным воротом. Яркий акцент дополняют контрастный принт. Идеально подойдет для тренировки.", "XS, S, M, L", new BigDecimal("999"), new BigDecimal("40"), 0),


                    //shirts
                    ProductInfoDTO.of("SHI001", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2325361.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2325356.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2325359.jpg", "men-home", "shirts", "MEDICINE - РУБАШКА BASIC", "100% Лен", "Рубашка из коллекции Medicine. Модель выполнена из гладкой ткани. Мягкий классический воротник типа kent. Рукава с манжетами на застежке. Застегивается на пуговицы. Крой regular. Карманчик на груди. Длина рукава: 67 см. Длина: 76 см. Ширина подмышками: 54 см. Ширина в плечах: 44 см. Параметры указаны для размера: M.", "XS, S, M, L", new BigDecimal("1399"), new BigDecimal("0"), 100),
                    ProductInfoDTO.of("SHI002", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2325362.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2325364.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2325365.jpg", "men-home", "shirts", "MEDICINE - РУБАШКА BASIC", "100% Лен", "Рубашка из коллекции Medicine. Модель выполнена из гладкой ткани. Мягкий классический воротник типа kent. Рукава с манжетами на застежке. Застегивается на пуговицы. Крой regular. Карманчик на груди. Длина рукава: 67 см. Длина: 76 см. Ширина подмышками: 54 см. Ширина в плечах: 44 см. Параметры указаны для размера: M.", "XS, S, M, L", new BigDecimal("1399"), new BigDecimal("20"), 100),
                    ProductInfoDTO.of("SHI003", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2331330.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2325377.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2325380.jpg", "men-home", "shirts", "MEDICINE - РУБАШКА BASIC", "45% Хлопок, 55% Лен", "Рубашка из коллекции Medicine. Модель выполнена из гладкой ткани. Имеет воротник button-down. Крой regular. Слегка уплотненный воротник button-down. Застегивается на пуговицы. Гладкая ткань. Ширина подмышками: 53,5 см. Ширина в плечах: 43,5 см. Длина рукава: 66,5 см. Длина: 73 см. Параметры указаны для размера: M.", "XS, S, M, L", new BigDecimal("999"), new BigDecimal("30"), 100),
                    ProductInfoDTO.of("SHI004", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2349792.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2349794.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2349795.jpg", "men-home", "shirts", "MEDICINE - РУБАШКА NATURE NEUTRAL", "45% Хлопок, 55% Лен", "Рубашка из коллекции Medicine. Модель выполнена из узорной ткани. Имеет полужесткий воротник на пуговицах.Узор: узорные.Крой: regular.Рукав: длинный.Материал: лён в составе. Повод: casual.Воротник: баттен даун", "XS, S, M, L", new BigDecimal("1099"), new BigDecimal("40"), 0),
                    ProductInfoDTO.of("SHI005", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2349787.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2349789.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2349790.jpg", "men-home", "shirts", "MEDICINE - РУБАШКА NATURE NEUTRAL", "45% Хлопок, 55% Лен", "Рубашка из коллекции Medicine. Модель выполнена из гладкой ткани. Имеет мягкий воротник на пуговицах.Узор: однотонные.Крой: regular.Рукав: длинный.Материал: лён в составе. Повод: casual.Воротник: баттен даун", "XS, S, M, L", new BigDecimal("1099"), new BigDecimal("60"), 100),
                    ProductInfoDTO.of("SHI006", "https://img.ans-media.com/files/sc_staging_images/product/large_img_1648900.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_1648901.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_1648903.jpg", "men-home", "shirts", "POLO RALPH LAUREN - РУБАШКА", "100% Хлопок", "Рубашка из коллекции Polo Ralph Lauren. Модель выполнена из гладкой ткани. Крой slim. Рукава с манжетами на застежке. Мягкий воротник типа button-down. Застегивается на пуговицы. Гладкая ткань. Длина рукава: 66 см. Длина: 76 см. Ширина подмышками: 52 см. Ширина в плечах: 43 см. Параметры указаны для размера: M.", "XS, S, M, L", new BigDecimal("2899"), new BigDecimal("0"), 100),
                    ProductInfoDTO.of("SHI007", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2431245.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2431247.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2431248.jpg", "men-home", "shirts", "TOM TAILOR DENIM - РУБАШКА", "100% Лен", "Рубашка из коллекции Tom Tailor Denim. Модель выполнена из узорной ткани. Имеет класический воротник.- Облегающий фасон. Короткий рукав. Карманчик на груди. Мягкий классический воротник типа kent. Застегивается на пуговицы. Узорчатая ткань. Длина: 70 см. Ширина подмышками: 52 см. Ширина в плечах: 42 см. Параметры указаны для размера: M.", "XS, S, M, L", new BigDecimal("1299"), new BigDecimal("20"), 100),
                    ProductInfoDTO.of("SHI008", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2349759.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2349761.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2349762.jpg", "men-home", "shirts", "MEDICINE - РУБАШКА BASIC", "55% Лен, 45% Хлопок", "Рубашка из коллекции Medicine. Модель выполнена из гладкой ткани. Имеет воротник-стойку. Узор: однотонные. Крой: slim. Рукав: длинный. Материал: лёню. Повод: casual. Воротник: стойка.", "XS, S, M, L", new BigDecimal("1099"), new BigDecimal("20"), 100),

                    //jeans
                    ProductInfoDTO.of("JE001", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2421112.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2421111.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2421113.jpg", "men-home", "jeans", "BRAVE SOUL - ДЖИНСЫ", "98% Хлопок, 2% Эластан", "Джинсы из коллекции Brave Soul типа skinny с обычной талией. Модель выполнена из стираного денима.", "XS, S, M, L", new BigDecimal("1099"), new BigDecimal("0"), 100),
                    ProductInfoDTO.of("JE002", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2307115.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2307116.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2307119.jpg", "men-home", "jeans", "G-STAR RAW - ДЖИНСЫ D-STAQ", "98% Органический хлопок, 2% Эластан", "Джинсы из коллекции G-Star Raw типа slim с обычной талией. Модель выполнена из стираного денима.", "XS, S, M, L", new BigDecimal("4299"), new BigDecimal("20"), 100),
                    ProductInfoDTO.of("JE003", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2132059.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2132058.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2132060.jpg", "men-home", "jeans", "LEVI'S - ДЖИНСЫ 512", "98% Хлопок, 2% Эластан", "Джинсы из коллекции Levi's типа slim tapered с обычной талией. Модель выполнена из стираного денима. Согласно политике охраны товарных знаков примерно 10% ассортимента бренда Levi's имеют \"пустой ярлык\" (красного цвета без логотипа бренда, исключительно с международным знаком торговой марки). \"Пустой ярлык\" - это зарегистрированный товарный знак бренда Levi's и модель, имеющая данный ярлык, является полноценным оригинальным продуктом. В случаях неуверенности, просим связаться с нашим call-centre.", "XS, S, M, L", new BigDecimal("2899"), new BigDecimal("0"), 100),
                    ProductInfoDTO.of("JE004", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2467068.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2467067.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2467069.jpg", "men-home", "jeans", "LEVI'S - ДЖИНСЫ", "100% Хлопок", "Джинсы из коллекции Levi's типа slim tapered с обычной талией. Модель выполнена из стираного денима.", "XS, S, M, L", new BigDecimal("2799"), new BigDecimal("30"), 100),
                    ProductInfoDTO.of("JE005", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2143890.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2143889.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2143891.jpg", "men-home", "jeans", "LEVI'S - ДЖИНСЫ 511", "98% Хлопок, 2% Эластан", "Джинсы из коллекции Levi's типа slim с обычной талией. Модель выполнена из стираного денима.", "XS, S, M, L", new BigDecimal("2799"), new BigDecimal("40"), 100),
                    ProductInfoDTO.of("JE006", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2442285.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2442284.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2442286.jpg", "men-home", "jeans", "DIESEL - ДЖИНСЫ SLEENKER", "94% Хлопок, 2% Эластан, 4% Полиэстер", "Джинсы из коллекции Diesel типа skinny с обычной талией. Модель выполнена из гладкого денима.", "XS, S, M, L", new BigDecimal("5399"), new BigDecimal("0"), 100),
                    ProductInfoDTO.of("JE007", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2435229.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2435228.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2435230.jpg", "men-home", "jeans", "LEVI'S - ДЖИНСЫ 502", "98% Хлопок, 2% Эластан", "Джинсы из коллекции Levi's типа tapered с обычной талией. Модель выполнена из стираного денима.", "XS, S, M, L", new BigDecimal("2899"), new BigDecimal("20"), 0),
                    ProductInfoDTO.of("JE008", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2249093.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2249092.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2249094.jpg", "men-home", "jeans", "MEDICINE - ДЖИНСЫ DENIM DAYS", "2% Эластан, 98% Хлопок", "Джинсы из коллекции Medicine типа slim с обычной талией. Модель выполнена из стираного денима.", "XS, S, M, L", new BigDecimal("1399"), new BigDecimal("0"), 0),

                    //shorts
                    ProductInfoDTO.of("SH001", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2209317.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2209316.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2209318.jpg", "men-home", "shorts", "CALVIN KLEIN - ШОРТЫ", "100% Хлопок", "Шорты из коллекции Calvin Klein. Модель выполнена из денима.", "XS, S, M, L", new BigDecimal("1999"), new BigDecimal("20"), 100),
                    ProductInfoDTO.of("SH002", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2417984.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2417983.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2417985.jpg", "men-home", "shorts", "MEDICINE - ДЖИНСОВЫЕ ШОРТЫ", "2% Эластан, 98% Хлопок", "Шорты из коллекции Medicine. Модель выполнена из денима.", "XS, S, M, L", new BigDecimal("1099"), new BigDecimal("0"), 100),
                    ProductInfoDTO.of("SH003", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2411076.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2411075.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2411077.jpg", "men-home", "shorts", "GUESS JEANS - ДЖИНСОВЫЕ ШОРТЫ", "64% Хлопок, 2% Эластан, 18% Полиэстер, 16% Вискоза", "Шорты из коллекции Guess Jeans. Модель выполнена из денима.", "XS, S, M, L", new BigDecimal("2699"), new BigDecimal("0"), 100),
                    ProductInfoDTO.of("SH004", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2308174.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2308173.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2308175.jpg", "men-home", "shorts", "ADIDAS PERFORMANCE - ШОРТЫ", "100% Вторичный полиэстер", "Гопник стайл", "XS, S, M, L", new BigDecimal("399"), new BigDecimal("10"), 0),
                    ProductInfoDTO.of("SH005", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2224956.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2224955.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2224957.jpg", "men-home", "shorts", "ADIDAS ORIGINALS - ШОРТЫ", "81% Хлопок, 19% Полиэстер", "Шорты из коллекции adidas Originals. Модель выполнена из денима.", "XS, S, M, L", new BigDecimal("1299"), new BigDecimal("40"), 100),
                    ProductInfoDTO.of("SH006", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2442739.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2442738.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2442740.jpg", "men-home", "shorts", "ADIDAS PERFORMANCE - ШОРТЫ", "100% Вторичный полиэстер", "Шорты из коллекции adidas Performance. Модель выполнена из денима.", "XS, S, M, L", new BigDecimal("649"), new BigDecimal("10"), 100),
                    ProductInfoDTO.of("SH007", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2429826.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2429825.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2429827.jpg", "men-home", "shorts", "ONLY & SONS - ШОРТЫ", "100% Хлопок", "Шорты из коллекции Only & Sons. Модель выполнена из денима.", "XS, S, M, L", new BigDecimal("749"), new BigDecimal("0"), 100),
                    ProductInfoDTO.of("SH008", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2435225.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2435224.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2435226.jpg", "men-home", "shorts", "LEVI'S - ДЖИНСОВЫЕ ШОРТЫ 501", "96% Хлопок, 2% Эластан, 2% Полиэстер", "Шорты из коллекции Levi's. Модель выполнена из денима.", "XS, S, M, L", new BigDecimal("1799"), new BigDecimal("0"), 100),

                    //jackets
                    ProductInfoDTO.of("JA001", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2446733.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2446732.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2446734.jpg", "men-home", "jackets", "BRAVE SOUL - ДЖИНСОВАЯ КУРТКА", "100% Хлопок", "Куртка из коллекции Brave Soul. Переходная модель выполнена из денима.", "XS, S, M, L", new BigDecimal("1299"), new BigDecimal("0"), 100),
                    ProductInfoDTO.of("JA002", "https://img.ans-media.com/files/sc_staging_images/product/large_img_1875932.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_1875931.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_1875933.jpg", "men-home", "jackets", "WRANGLER - КУРТКА", "100% Хлопок", "Куртка из коллекции Wrangler. Легкая модель выполнена из денима.", "XS, S, M, L", new BigDecimal("2699"), new BigDecimal("0"), 100),
                    ProductInfoDTO.of("JA003", "https://img.ans-media.com/files/sc_staging_images/product/large_img_1790288.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_1790283.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_1790284.jpg", "men-home", "jackets", "WRANGLER - ДЖИНСОВАЯ КУРТКА", "100% Хлопок", "Куртка из коллекции Wrangler. Легкая модель выполнена из денима.", "XS, S, M, L", new BigDecimal("2799"), new BigDecimal("20"), 100),
                    ProductInfoDTO.of("JA004", "https://img.ans-media.com/files/sc_staging_images/product/large_img_1628995.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_1628994.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_1628996.jpg", "men-home", "jackets", "LEVI'S - КУРТКА", "76% Хлопок, 24% Лиоцелл", "Куртка из коллекции Levi's. Легкая модель выполнена из денима.", "XS, S, M, L", new BigDecimal("3299"), new BigDecimal("30"), 100),
                    ProductInfoDTO.of("JA005", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2453100.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2453099.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2453101.jpg", "men-home", "jackets", "CALVIN KLEIN JEANS - ДЖИНСОВАЯ КУРТКА", "99% Хлопок, 1% Эластан", "Куртка из коллекции Calvin Klein Jeans. Переходная модель выполнена из денима.", "XS, S, M, L", new BigDecimal("4299"), new BigDecimal("0"), 100),
                    ProductInfoDTO.of("JA006", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2421074.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2421075.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2421076.jpg", "men-home", "jackets", "BRAVE SOUL - КУРТКА", "100% Полиуретан", "Куртка из коллекции Brave Soul. Переходная модель выполнена из искусственной кожи.", "XS, S, M, L", new BigDecimal("2999"), new BigDecimal("40"), 100),
                    ProductInfoDTO.of("JA007", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2416217.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2416218.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2416219.jpg", "men-home", "jackets", "GUESS JEANS - КУРТКА", "100% Полиэстер", "Куртка из коллекции Guess Jeans. Неутепленая модель выполнена из узорного материала.", "XS, S, M, L", new BigDecimal("4999"), new BigDecimal("20"), 100),
                    ProductInfoDTO.of("JA008", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2248969.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2248968.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2248970.jpg", "men-home", "jackets", "MEDICINE - КУРТКА DENIM DAYS", "100% Полиуретан", "Куртка из коллекции Medicine. Неутепленая модель выполнена из искусственной кожи.", "XS, S, M, L", new BigDecimal("1299"), new BigDecimal("0"), 100),

                    // women-home
                    //t-shirts
                    ProductInfoDTO.of("WTS001", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2433148.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2433149.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2433150.jpg", "women-home", "t-shirts", "ANSWEAR - ФУТБОЛКА ANSWEAR LAB", "100% Хлопок", "Футболка из коллекции Answear. Модель выполнена из тонкого эластичного трикотажа.", "XS, S, M, L", new BigDecimal("499"), new BigDecimal("0"), 100),
                    ProductInfoDTO.of("WTS002", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2230362.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2230363.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2230364.jpg", "women-home", "t-shirts", "TOMMY JEANS - ТОП", "57% Хлопок, 5% Эластан, 38% Полиэстер", "Топ из коллекции Tommy Jeans. Модель выполнена из трикотажа с принтом.", "XS, S, M, L", new BigDecimal("1399"), new BigDecimal("0"), 100),
                    ProductInfoDTO.of("WTS003", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2206589.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2206592.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2206593.jpg", "women-home", "t-shirts", "CALVIN KLEIN JEANS - ТОП", "95% Хлопок, 5% Эластан", "Топ из коллекции Calvin Klein Jeans. Модель выполнена из трикотажа с принтом.", "XS, S, M, L", new BigDecimal("1399"), new BigDecimal("20"), 100),
                    ProductInfoDTO.of("WTS004", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2021422.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2021423.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2021424.jpg", "women-home", "t-shirts", "TOMMY SPORT - МАЙКА", "100% Полиэстер", "Майка из коллекции Tommy Sport. Модель выполнена из трикотажа с принтом.", "XS, S, M, L", new BigDecimal("1649"), new BigDecimal("0"), 100),
                    ProductInfoDTO.of("WTS005", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2454171.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2454172.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2454173.jpg", "women-home", "t-shirts", "FEMI STORIES - МАЙКА RUT", "100% Вискоза", "Майка из коллекции Femi Stories. Модель выполнена из узорного материала.", "XS, S, M, L", new BigDecimal("1099"), new BigDecimal("40"), 0),
                    ProductInfoDTO.of("WTS006", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2445744.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2445743.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2445745.jpg", "women-home", "t-shirts", "ANSWEAR - ФУТБОЛКА ANSWEAR LAB", "100% Хлопок", "Свободная футболка из коллекции Answear. Модель выполнена из тонкого эластичного трикотажа.", "XS, S, M, L", new BigDecimal("749"), new BigDecimal("20"), 100),
                    ProductInfoDTO.of("WTS007", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2425138.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2425139.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2425140.jpg", "women-home", "t-shirts", "GUESS JEANS - ФУТБОЛКА", "100% Органический хлопок", "Футболка из коллекции Guess Jeans. Модель выполнена из тонкого эластичного трикотажа.", "XS, S, M, L", new BigDecimal("1399"), new BigDecimal("0"), 100),
                    ProductInfoDTO.of("WTS008", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2427357.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2427358.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2427359.jpg", "women-home", "t-shirts", "GUESS JEANS - ФУТБОЛКА", "95% Хлопок, 5% Эластан", "Приталенная футболка из коллекции Guess Jeans. Модель выполнена из тонкого эластичного трикотажа.", "XS, S, M, L", new BigDecimal("1099"), new BigDecimal("30"), 100),

                    // shorts
                    ProductInfoDTO.of("WSH001", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2431632.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2431633.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2431634.jpg", "women-home", "shorts", "ADIDAS ORIGINALS - ШОРТЫ", "100% Полиэстер", "Шорты из коллекции adidas Originals. Модель выполнена из денима.", "XS, S, M, L", new BigDecimal("799"), new BigDecimal("0"), 100),
                    ProductInfoDTO.of("WSH002", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2411971.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2411972.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2411973.jpg", "women-home", "shorts", "MEDICINE - ШОРТЫ POWER OF NATURE", "100% Лиоцелл", "Шорты из коллекции Medicine. Модель выполнена из комфортного материала", "XS, S, M, L", new BigDecimal("799"), new BigDecimal("0"), 100),
                    ProductInfoDTO.of("WSH003", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2427896.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2427897.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2427895.jpg", "women-home", "shorts", "PUMA - ШОРТЫ", "5% Эластан, 95% Хлопок", "Шорты из коллекции Puma. Модель выполнена из комфортного материала.", "XS, S, M, L", new BigDecimal("999"), new BigDecimal("0"), 100),
                    ProductInfoDTO.of("WSH004", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2468926.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2468925.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2468927.jpg", "women-home", "shorts", "GUESS JEANS - ШОРТЫ", "62% Полиэстер, 38% Вискоза", "Шорты из коллекции Guess Jeans. Модель выполнена из гладкого материала.", "XS, S, M, L", new BigDecimal("1399"), new BigDecimal("20"), 100),
                    ProductInfoDTO.of("WSH005", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2392089.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2392088.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2392090.jpg", "women-home", "shorts", "ADIDAS ORIGINALS - ШОРТЫ", "49% Хлопок, 51% Полиэстер", "Шорты из коллекции adidas Originals. Модель выполнена из комфортного материала.", "XS, S, M, L", new BigDecimal("1099"), new BigDecimal("10"), 100),
                    ProductInfoDTO.of("WSH006", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2341399.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2341400.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2341401.jpg", "women-home", "shorts", "ANSWEAR - ДЖИНСОВЫЕ ШОРТЫ", "99% Хлопок, 1% Эластан", "Шорты из коллекции Answear. Модель выполнена из денима.", "XS, S, M, L", new BigDecimal("999"), new BigDecimal("25"), 100),
                    ProductInfoDTO.of("WSH007", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2125990.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2125991.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2125992.jpg", "women-home", "shorts", "MEDICINE - ШОРТЫ BASIC", "100% Лиоцелл", "Шорты из коллекции Medicine. Модель выполнена из денима.", "XS, S, M, L", new BigDecimal("999"), new BigDecimal("40"), 100),
                    ProductInfoDTO.of("WSH008", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2442001.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2442002.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2442003.jpg", "women-home", "shorts", "MANGO - ДЖИНСОВЫЕ ШОРТЫ BERMUDA", "100% Хлопок", "Шорты из коллекции Mango. Модель выполнена из денима.", "XS, S, M, L", new BigDecimal("999"), new BigDecimal("0"), 0),

                    // hoodies
                    ProductInfoDTO.of("WJE001", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2452362.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2452363.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2452364.jpg", "women-home", "hoodies", "GUESS JEANS - КОФТА", "100% Хлопок", "Кофта с капюшоном из коллекции Guess Jeans. Модель с застежкой на молнию выполнена из тонкого, легко эластичного трикотажа.", "XS, S, M, L", new BigDecimal("1589"), new BigDecimal("0"), 100),
                    ProductInfoDTO.of("WJE002", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2453982.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2453983.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2453984.jpg", "women-home", "hoodies", "GUESS JEANS - КОФТА", "100% Хлопок", "Кофта с капюшоном из коллекции Guess Jeans. Модель с застежкой на молнию выполнена из тонкого, легко эластичного трикотажа.", "XS, S, M, L", new BigDecimal("1589"), new BigDecimal("10"), 100),
                    ProductInfoDTO.of("WJE003", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2210739.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2210740.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2210741.jpg", "women-home", "hoodies", "CALVIN KLEIN JEANS - КОФТА", "100% Хлопок", "Кофта из коллекции Calvin Klein Jeans. Модель выполнена из трикотажа с принтом.", "XS, S, M, L", new BigDecimal("2899"), new BigDecimal("0"), 100),
                    ProductInfoDTO.of("WJE004", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2287597.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2287598.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2287599.jpg", "women-home", "hoodies", "CALVIN KLEIN JEANS - КОФТА", "100% Хлопок", "Кофта из коллекции Calvin Klein Jeans. Модель выполнена из трикотажа с апликацией.", "XS, S, M, L", new BigDecimal("3199"), new BigDecimal("20"), 100),
                    ProductInfoDTO.of("WJE005", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2443880.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2443881.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2443882.jpg", "women-home", "hoodies", "DIESEL - КОФТА", "52% Хлопок, 33% Нейлон, 15% Полиэстер", "Кофта из коллекции Diesel. Модель выполнена из тонкого эластичного трикотажа.", "XS, S, M, L", new BigDecimal("6999"), new BigDecimal("0"), 100),
                    ProductInfoDTO.of("WJE006", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2472769.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2472773.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2472774.jpg", "women-home", "hoodies", "LOVE MOSCHINO - КОФТА", "100% Хлопок", "Кофта с капюшоном из коллекции Love Moschino. Модель выполнена из трикотажа с апликацией.", "XS, S, M, L", new BigDecimal("6399"), new BigDecimal("0"), 100),
                    ProductInfoDTO.of("WJE007", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2426887.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2426888.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2426889.jpg", "women-home", "hoodies", "DIESEL - КОФТА", "100% Хлопок", "Кофта из коллекции Diesel. Модель выполнена из гладкого трикотажа.", "XS, S, M, L", new BigDecimal("5999"), new BigDecimal("0"), 100),
                    ProductInfoDTO.of("WJE008", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2472588.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2472589.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2472590.jpg", "women-home", "hoodies", "LOVE MOSCHINO - КОФТА", "100% Хлопок", "Кофта из коллекции Love Moschino. Модель выполнена из тонкого эластичного трикотажа.", "XS, S, M, L", new BigDecimal("5999"), new BigDecimal("40"), 100),

                    // skirts
                    ProductInfoDTO.of("WSK001", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2440166.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2440167.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2440168.jpg", "women-home", "skirts", "RED VALENTINO - ЮБКА", "6% Эластан, 80% Полиэстер, 14% Вискоза", "Юбка из коллекции Red Valentino. Модель расклешенного фасону, выполнена из тонкой, легко эластичной ткани.", "XS, S, M, L", new BigDecimal("7999"), new BigDecimal("0"), 100),
                    ProductInfoDTO.of("WSK002", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2440182.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2440183.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2440184.jpg", "women-home", "skirts", "RED VALENTINO - ЮБКА", "100% Полиэстер", "Юбка из коллекции Red Valentino. Модель расклешенного фасону, выполнена из гладкой ткани.", "XS, S, M, L", new BigDecimal("16999"), new BigDecimal("0"), 100),
                    ProductInfoDTO.of("WSK003", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2472620.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2472621.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2472622.jpg", "women-home", "skirts", "LOVE MOSCHINO - ЮБКА", "100% Полиэстер", "Юбка из коллекции Love Moschino. Модель расклешенного фасону, выполнена из узорной ткани.", "XS, S, M, L", new BigDecimal("8999"), new BigDecimal("0"), 100),
                    ProductInfoDTO.of("WSK004", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2434406.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2434407.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2434408.jpg", "women-home", "skirts", "KARL LAGERFELD - ЮБКА", "100% Полиэстер", "Юбка из коллекции Karl Lagerfeld. Модель расклешенного фасону, выполнена из узорной ткани.", "XS, S, M, L", new BigDecimal("7999"), new BigDecimal("0"), 100),
                    ProductInfoDTO.of("WSK005", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2427850.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2427851.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2427852.jpg", "women-home", "skirts", "ROBERTO CAVALLI SPORT - ЮБКА", "100% Полиэстер", "Юбка из коллекции Roberto Cavalli Sport. Модель расклешенного фасону, выполнена из узорной ткани.", "XS, S, M, L", new BigDecimal("8999"), new BigDecimal("20"), 100),
                    ProductInfoDTO.of("WSK006", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2265941.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2265942.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2265943.jpg", "women-home", "skirts", "RED VALENTINO - ЮБКА", "100% Полиэстер", "Юбка из коллекции Red Valentino. Модель расклешенного кроя, выполнена из кружевного материала.", "XS, S, M, L", new BigDecimal("20999"), new BigDecimal("60"), 100),
                    ProductInfoDTO.of("WSK007", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2287390.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2287391.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2287392.jpg", "women-home", "skirts", "LIU JO - ЮБКА", "100% Полиуретан", "Юбка из коллекции Liu Jo. Модель прямого кроя, выполнена из гладкого трикотажа.", "XS, S, M, L", new BigDecimal("4999"), new BigDecimal("0"), 100),
                    ProductInfoDTO.of("WSK008", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2178035.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2178036.jpg", "https://img.ans-media.com/files/sc_staging_images/product/large_img_2178037.jpg", "women-home", "skirts", "PATRIZIA PEPE - ЮБКА", "30% Акрил, 56% Хлопок, 10% Полиамид, 4% Полиэстер", "Юбка из коллекции Patrizia Pepe. Модель прямого кроя, выполнена из узорной ткани.", "XS, S, M, L", new BigDecimal("7999"), new BigDecimal("40"), 100),

                    // dresses
                    ProductInfoDTO.of("WDR001", "https://a.lmcdn.ru/product/M/A/MA002EWJIYE4_11156484_1_v1.jpg", "https://a.lmcdn.ru/product//M/A/MA002EWJIYE4_11156486_3_v1.jpg", "https://a.lmcdn.ru/product//M/A/MA002EWJIYE4_11156485_2_v1.jpg", "women-home", "dresses", "MANGO Платье - SEUL", "Хлопок-100%", "Сезон: мульти; Цвет: бежевый; Узор: однотонный; Карманы: 4; Комплектация: пояс; Страна производства: Китай; Застежка: пуговицы", "XS, S, M, L", new BigDecimal("1399"), new BigDecimal("30"), 100),
                    ProductInfoDTO.of("WDR002", "https://a.lmcdn.ru/product/M/A/MA002EWJKLL2_11244195_1_v1.jpg", "https://a.lmcdn.ru/product//M/A/MA002EWJKLL2_11244196_2_v1.jpg", "https://a.lmcdn.ru/product//M/A/MA002EWJKLL2_11244197_3_v1.jpg", "women-home", "dresses", "MANGO Платье - TEMPOLI", "Лен-55%, Вискоза-45%", "Сезон: мульти; Цвет: бежевый; Узор: полоска; Страна производства: Вьетнам; Застежка: шнурки", "XS, S, M, L", new BigDecimal("1999"), new BigDecimal("25"), 100),
                    ProductInfoDTO.of("WDR003", "https://a.lmcdn.ru/product/M/A/MA002EWIRKE8_10558215_1_v1.jpg", "https://a.lmcdn.ru/product//M/A/MA002EWIRKE8_10558216_2_v1.jpg", "https://a.lmcdn.ru/product//M/A/MA002EWIRKE8_10558217_3_v1.jpg", "women-home", "dresses", "MANGO Платье - SAIMI", "Вискоза-100%", "Сезон: мульти; Цвет: мультиколор; Узор: цветочный; Страна производства: Марокко; Застежка: без застежки", "XS, S, M, L", new BigDecimal("3599"), new BigDecimal("60"), 100),
                    ProductInfoDTO.of("WDR004", "https://a.lmcdn.ru/product/M/A/MA002EWIRLW4_10558558_1_v1.jpg", "https://a.lmcdn.ru/product//M/A/MA002EWIRLW4_10558559_2_v1.jpg", "https://a.lmcdn.ru/product//M/A/MA002EWIRLW4_10558560_3_v1.jpg", "women-home", "dresses", "MANGO Платье - SIA", "Полиэстер-100%", "Сезон: мульти; Цвет: мультиколор; Узор: цветочный; Страна производства: Марокко; Застежка: без застежки", "XS, S, M, L", new BigDecimal("3599"), new BigDecimal("44"), 100),
                    ProductInfoDTO.of("WDR005", "https://a.lmcdn.ru/product/C/A/CA994EWHVML7_11361544_1_v1_2x.jpg", "https://a.lmcdn.ru/product//C/A/CA994EWHVML7_11361545_2_v1_2x.jpg", "https://a.lmcdn.ru/product//C/A/CA994EWHVML7_11361546_3_v1_2x.jpg", "women-home", "dresses", "Calvin Klein Underwear Платье пляжное", "Вискоза-100%", "Размер товара на модели: S; Параметры модели: 84-61-92; Рост модели на фото: 177; Сезон: лето; Цвет: белый; Узор: однотонный; Страна производства: Китай", "XS, S, M, L", new BigDecimal("2470"), new BigDecimal("20"), 100),
                    ProductInfoDTO.of("WDR006", "https://a.lmcdn.ru/product/M/P/MP002XW10440_11312093_1_v4.jpeg", "https://a.lmcdn.ru/product//M/P/MP002XW10440_11312095_2_v4.jpeg", "https://a.lmcdn.ru/product//M/P/MP002XW10440_11312094_3_v4.jpeg", "women-home", "dresses", "Sewel Платье", " Хлопок-50%, Акрил-50%", "Утеплитель: без утеплителя; Размер товара на модели: 46-48; Параметры модели: 90-64-95; Рост модели на фото: 179; Сезон: мульти; Цвет: розовый; Узор: однотонный", "XS, S, M, L", new BigDecimal("660"), new BigDecimal("40"), 100),
                    ProductInfoDTO.of("WDR007", "https://a.lmcdn.ru/product/O/N/ON380EWHSBW9_10929525_1_v1_2x.jpg", "https://a.lmcdn.ru/product//O/N/ON380EWHSBW9_10929526_2_v1_2x.jpg", "https://a.lmcdn.ru/product//O/N/ON380EWHSBW9_10929527_3_v1_2x.jpg", "women-home", "dresses", "Only Платье", " Лиоцелл-100%", "Параметры модели: 84-60-92; Рост модели на фото: 178; Сезон: лето; Цвет: голубой; Узор: однотонный; Страна производства: Китай; Застежка: молния", "XS, S, M, L", new BigDecimal("1400"), new BigDecimal("0"), 100),
                    ProductInfoDTO.of("WDR008", "https://a.lmcdn.ru/product/M/P/MP002XW0HUEK_10259956_1_v1.jpeg", "https://a.lmcdn.ru/product//M/P/MP002XW0HUEK_10259957_2_v1.jpeg", "https://a.lmcdn.ru/product/M/P/MP002XW0HUEK_10259956_1_v1.jpeg", "women-home", "dresses", "Ora Платье", "Лен-55%, Хлопок-45%", "Размер товара на модели: S; Параметры модели: 85-60-88; Рост модели на фото: 173; Сезон: лето;  Цвет: белый; Узор: полоска; Талия: стандартная", "XS, S, M, L", new BigDecimal("999"), new BigDecimal("40"), 100)

            );

            productService.addProducts(Products);
        };
    }
}
